### ISSUE TITLE
Porting to NWB v2

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/IPNWB#5]
#### Cross links

https://github.com/AllenInstitute/MIES/issues/22
https://github.com/AllenInstitute/MIES/pull/179 (TODO list)
https://github.com/AllenInstitute/IPNWB/issues/5
https://github.com/AllenInstitute/IPNWB/pull/16

**Comment by t-b** [comment]
@timjarsky

**Comment by t-b** [comment]
- Please base the work on the branch https://github.com/AllenInstitute/IPNWB/tree/make-all-functions-threadsafe.

**Comment by ukos-git** [comment]
https://github.com/AllenInstitute/MIES/pull/179
